apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: syslog-ng
  name: syslog-ng
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: syslog-ng
    spec:
      containers:
      - args:
        - /usr/sbin/syslog-ng
        - -F
        env:
        - name: DB_HOST
          value: db
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: syslog-ng-librenms-env
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWORD
              name: syslog-ng-librenms-env
        - name: DB_TIMEOUT
          value: "30"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: syslog-ng-librenms-env
        - name: LIBRENMS_CRON_ALERTS_ENABLE
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_CRON_ALERTS_ENABLE
              name: syslog-ng-librenms-env
        - name: LIBRENMS_CRON_BILLING_CALCULATE_ENABLE
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_CRON_BILLING_CALCULATE_ENABLE
              name: syslog-ng-librenms-env
        - name: LIBRENMS_CRON_BILLING_ENABLE
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_CRON_BILLING_ENABLE
              name: syslog-ng-librenms-env
        - name: LIBRENMS_CRON_CHECK_SERVICES_ENABLE
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_CRON_CHECK_SERVICES_ENABLE
              name: syslog-ng-librenms-env
        - name: LIBRENMS_CRON_DAILY_ENABLE
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_CRON_DAILY_ENABLE
              name: syslog-ng-librenms-env
        - name: LIBRENMS_CRON_DISCOVERY_ENABLE
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_CRON_DISCOVERY_ENABLE
              name: syslog-ng-librenms-env
        - name: LIBRENMS_CRON_POLLER_ENABLE
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_CRON_POLLER_ENABLE
              name: syslog-ng-librenms-env
        - name: LIBRENMS_POLLER_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_POLLER_INTERVAL
              name: syslog-ng-librenms-env
        - name: LIBRENMS_POLLER_THREADS
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_POLLER_THREADS
              name: syslog-ng-librenms-env
        - name: LIBRENMS_SNMP_COMMUNITY
          valueFrom:
            configMapKeyRef:
              key: LIBRENMS_SNMP_COMMUNITY
              name: syslog-ng-librenms-env
        - name: MEMCACHED_HOST
          valueFrom:
            configMapKeyRef:
              key: MEMCACHED_HOST
              name: syslog-ng-librenms-env
        - name: MEMCACHED_PORT
          valueFrom:
            configMapKeyRef:
              key: MEMCACHED_PORT
              name: syslog-ng-librenms-env
        - name: MEMORY_LIMIT
          valueFrom:
            configMapKeyRef:
              key: MEMORY_LIMIT
              name: syslog-ng-librenms-env
        - name: OPCACHE_MEM_SIZE
          valueFrom:
            configMapKeyRef:
              key: OPCACHE_MEM_SIZE
              name: syslog-ng-librenms-env
        - name: PGID
        - name: PUID
        - name: RRDCACHED_HOST
          valueFrom:
            configMapKeyRef:
              key: RRDCACHED_HOST
              name: syslog-ng-librenms-env
        - name: RRDCACHED_PORT
          valueFrom:
            configMapKeyRef:
              key: RRDCACHED_PORT
              name: syslog-ng-librenms-env
        - name: TZ
        - name: UPLOAD_MAX_SIZE
          valueFrom:
            configMapKeyRef:
              key: UPLOAD_MAX_SIZE
              name: syslog-ng-librenms-env
        image: librenms/librenms:latest
        name: syslog-ng
        ports:
        - containerPort: 514
        - containerPort: 514
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: syslog-ng-claim0
      restartPolicy: Always
      volumes:
      - name: syslog-ng-claim0
        persistentVolumeClaim:
          claimName: syslog-ng-claim0
status: {}
