apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
      - args:
        - --logLevel=INFO
        - --defaultentrypoints=http,https
        - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
        - --entryPoints=Name:https Address::443 TLS
        - --docker
        - --docker.exposedbydefault=false
        - --docker.domain=
        - --acme=true
        - --acme.acmelogging=true
        - --acme.email=webmaster@example.com
        - --acme.storage=acme.json
        - --acme.entryPoint=https
        - --acme.onhostrule=true
        - --acme.httpchallenge=true
        - --acme.httpchallenge.entrypoint=http
        image: traefik:1.6-alpine
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /acme.json
          name: traefik-claim0
        - mountPath: /var/run/docker.sock
          name: traefik-claim1
      restartPolicy: Always
      volumes:
      - name: traefik-claim0
        persistentVolumeClaim:
          claimName: traefik-claim0
      - name: traefik-claim1
        persistentVolumeClaim:
          claimName: traefik-claim1
status: {}
